version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: constancy-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: constancy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - constancy-network

volumes:
  postgres_data:

networks:
  constancy-network:
    driver: bridge
